POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWQiOiJleGFtcGxlSWQiLCJpYXQiOjE2MjM2MTQ4MDB9.s2gB1FeRQsmCxH7IuNU6fUUNYFL4ZDz7fQgBWkm0Zm4

{
  "title": "auth testi",
  "author": "auth",
  "url": "testi.fi",
  "likes": 123
}
